# Generated by Django 4.2.5 on 2023-10-20 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_userprofile_bio_alter_userprofile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='picture',
        ),
        migrations.AlterField(
            model_name='post',
            name='create_at',
            field=models.DateTimeField(),
        ),
    ]
